version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'nuget'
    # folder to check the dependencies in
    directory: '/AzDoExtensionNews/'    
    # Check the registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /AzDoExtensionNews/AzDoExtensionNews.UnitTests
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /AzDoExtensionNews/AzDoExtensionNews
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /AzDoExtensionNews/GitHubActionsNews.Tests
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /AzDoExtensionNews/GitHubActionsNews
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /AzDoExtensionNews/News.Library
    schedule:
      interval: monthly
