version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all-in-one:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: nuget
    directory: 
     - /AzDoExtensionNews/AzDoExtensionNews.UnitTests
     - /AzDoExtensionNews/AzDoExtensionNews
     - /AzDoExtensionNews/GitHubActionsNews.Tests
     - /AzDoExtensionNews/GitHubActionsNews
     - /AzDoExtensionNews/News.Library
    schedule:
      interval: monthly
    groups:
      all-in-one:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

