name: 'character to run'
description: 'a description'

# Were we can define the inputs that our action will accept
inputs:
  characters: 
    required: true
  artifactName:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifactName }}
        path: ./ArtifactFolder

    - name: 'Show folder structure'
      shell: bash
      run: ls

    #   - name: App Settings Variable Substitution
    #     uses: microsoft/variable-substitution@v1
    #     with:
    #       files: '${{steps.download.outputs.download-path}}/drop/GH/appsettings.json/appsettings.json'
    #     env:
    #       TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
    #       TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
    #       TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
    #       TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
    #       BlobStorageConnectionString: ${{ secrets.BlobStorageConnectionString }}

    #   - name: Perform a Pester test from the command-line
    #     shell: pwsh
    #     run: |
    #       cd "${{steps.download.outputs.download-path}}/drop/GH/"
    #       dotnet .\GitHubActionsNews.dll ${{ inputs.characters }}
