name: 'character to run'
description: 'a description'

# Were we can define the inputs that our action will accept
inputs:
  characters: 
    required: true
  artifactName:
    required: true
  TwitterConsumerAPIKey:
    required: true
  TwitterConsumerAPISecretKey:
    required: true
  TwitterAccessToken:
    required: true
  TwitterAccessTokenSecret:
    required: true
  BlobStorageConnectionString:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifactName }}
        path: ./ArtifactFolder

      # https://github.com/microsoft/variable-substitution
      #Deprecated action, but it still works :-). Does need an update to node16 though!
    - name: App Settings Variable Substitution
      uses: rajbos/variable-substitution@main #@v1 
      with:
        files: 'ArtifactFolder/appsettings.json'
      env:
        TwitterConsumerAPIKey: ${{ inputs.TwitterConsumerAPIKey }}
        TwitterConsumerAPISecretKey: ${{ inputs.TwitterConsumerAPISecretKey }}
        TwitterAccessToken: ${{ inputs.TwitterAccessToken }}
        TwitterAccessTokenSecret: ${{ inputs.TwitterAccessTokenSecret }}
        BlobStorageConnectionString: ${{ inputs.BlobStorageConnectionString }}

    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: |
        cd .\ArtifactFolder        
        dotnet GitHubActionsNews.dll ${{ inputs.characters }}
