name: Scheduled Build and Deploy

env:
  ArtifactName: 'AzDoNews'

on:
  schedule:
    - cron: "15 */8 * * *"

  workflow_dispatch:
  
  push:
   paths:
   - .github/workflows/deploy.yml
   - .github/actions/character-to-run/*
   - .github/workflows/createBlogPostsFromUpdates.ps1 # temp!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3.5.3
    - uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release
      
    - name: Publish
      run: dotnet publish AzDoExtensionNews/AzDoExtensionNews.sln -c Release --property:PublishDir=${{ github.workspace }}/publish/AzDo/
      
    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        path: publish/AzDo
        name: ${{ env.ArtifactName }}

  GatherCharacter:
    runs-on: windows-latest
    needs: build
    continue-on-error: true
    concurrency: GatherCharacterJsons-${{ matrix.character }}
    strategy:
      matrix:
        character: [c,b,e,g,h,j,k,l,m,n,u,w,x,y,z,o,p,r,sa,sb,sc,sd,se,sf,sg,sh,sj,sk,sl,sm,sn,sp,sr,su,sv,sw,t,v,ai,ae,ia,ea,0,1,2,3,4,5,6,7,8,9]
        #character: [9] # temp for faster testing of consolidate updates
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3.5.3

      - name: Run Character Command
        uses: ./.github/actions/character-to-run/
        with:
          characters: ${{ matrix.character }}
          artifactName: ${{ env.ArtifactName }}
          # we don't need actual values for these in this job, but they are required
          TwitterConsumerAPIKey: 'TwitterConsumerAPIKey'
          TwitterConsumerAPISecretKey: 'TwitterConsumerAPISecretKey'
          TwitterAccessToken: 'TwitterAccessToken'
          TwitterAccessTokenSecret: 'TwitterAccessTokenSecret'
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

  ConsolidateUpdates:
    runs-on: windows-latest
    needs: GatherCharacter
    concurrency: there-can-only-be-one
    if: ${{ always() }}
    steps:
      - name: Handle matrix error
        run: |
          if ( "${{ needs.GatherCharacter.result }}" -eq "failure" ) {
            echo "All matrix jobs failed."
            exit 1
          }

      - name: Download artifact from build job
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: ${{ env.artifactName }}
          path: ./ArtifactFolder

      - name: App Settings Variable Substitution
        uses: rajbos-actions/variable-substitution@ae7b1f3676ae374dc70282e6b9650bc50b611222 # v1.2
        with:
          files: 'ArtifactFolder/appsettings.json'
        env:
          TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
          TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
          TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
          TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

      - name: Consolidate the json files and tweet about updates
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          dotnet GitHubActionsNews.dll "consolidate"

      - name: Show consolidated json
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          cat Actions-Updated-Overview.json
          Get-Content Actions-Updated-Overview.json
                
      - name: Upload Updated Json
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          path: ArtifactFolder/Actions-Updated-Overview.json
          name: UpdatedActions

  PostNews:
    runs-on: ubuntu-latest
    needs: ConsolidateUpdates
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: UpdatedActions
          path: ./ArtifactFolder

      - name: show data
        run: |
          ls -la
          cat ArtifactFolder/Actions-Updated-Overview.json

      - name: Create blogposts updates for updates
        shell: pwsh
        run: |
          ls
          cd .github/workflows/
          ls
          
          $filePath = Resolve-Path "..\..\ArtifactFolder\Actions-Updated-Overview.json"
          .\createBlogPostsFromUpdates.ps1 -token ${{ secrets.PAT }} -filePath $filePath
          
