name: Scheduled Build and Deploy

env:
  ArtifactName: 'AzDoNews'

on:
  schedule:
    - cron: "15 */8 * * *"

  workflow_dispatch:
  
  push:
   paths:
   - .github/workflows/deploy.yml
   - .github/actions/character-to-run/*
   - .github/workflows/createBlogPostsFromUpdates.ps1 # temp!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release
      
    - name: Publish
      run: dotnet publish AzDoExtensionNews/AzDoExtensionNews.sln -c Release --property:PublishDir=${{ github.workspace }}/publish/AzDo/
      
    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        path: publish/AzDo
        name: ${{ env.ArtifactName }}

  GatherCharacter:
    runs-on: windows-latest
    needs: build
    continue-on-error: true
    concurrency: GatherCharacterJsons-${{ matrix.character }}
    strategy:
      matrix:
        character: [c,b,e,g,h,j,k,l,m,n,u,w,x,y,z,o,p,r,sa,sb,sc,sd,se,sf,sg,sh,sj,sk,sl,sm,sn,sp,sr,su,sv,sw,t,v,ai,ae,ia,ea,0,1,2,3,4,5,6,7,8,9]
        #character: [9] # temp for faster testing of consolidate updates
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Run Character Command
        uses: ./.github/actions/character-to-run/
        with:
          characters: ${{ matrix.character }}
          artifactName: ${{ env.ArtifactName }}
          # we don't need actual values for these in this job, but they are required
          TwitterConsumerAPIKey: 'TwitterConsumerAPIKey'
          TwitterConsumerAPISecretKey: 'TwitterConsumerAPISecretKey'
          TwitterAccessToken: 'TwitterAccessToken'
          TwitterAccessTokenSecret: 'TwitterAccessTokenSecret'
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

  ConsolidateUpdates:
    runs-on: windows-latest
    needs: GatherCharacter
    concurrency: there-can-only-be-one
    if: ${{ always() }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Download artifact from build job
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ env.artifactName }}
          path: ./ArtifactFolder

      - name: App Settings Variable Substitution
        uses: rajbos-actions/variable-substitution@a4367a66ba128295f7dddf8964a0ac429766492d # v1.1
        with:
          files: 'ArtifactFolder/appsettings.json'
        env:
          TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
          TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
          TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
          TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

      - name: Consolidate the json files and tweet about updates
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          dotnet GitHubActionsNews.dll "consolidate"

      - name: Show consolidated json
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          cat Actions-Updated-Overview.json
          Get-Content Actions-Updated-Overview.json
                
      - name: Upload Updated Json
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: ArtifactFolder/Actions-Updated-Overview.json
          name: UpdatedActions

  PostNews:
    runs-on: ubuntu-latest
    needs: ConsolidateUpdates
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: UpdatedActions
          path: ./ArtifactFolder

      - name: show data
        run: |
          ls -la
          cat ArtifactFolder/Actions-Updated-Overview.json

      - name: Create blogposts updates for updates
        shell: pwsh
        run: |
          ls
          cd .github/workflows/
          ls
          
          $filePath = Resolve-Path "..\..\ArtifactFolder\Actions-Updated-Overview.json"
          .\createBlogPostsFromUpdates.ps1 -token ${{ secrets.PAT }} -filePath $filePath
          