name: Scheduled Build and Deploy

env:
  ArtifactName: 'AzDoNews'

on:
  schedule:
    - cron: "15 */5 * * *"

  workflow_dispatch:
  
  push:
   paths:
   - .github/workflows/deploy.yml
   - .github/actions/character-to-run/*
   - .github/workflows/createBlogPostsFromUpdates.ps1 # temp!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release
      
    - name: Publish
      run: dotnet publish AzDoExtensionNews/AzDoExtensionNews.sln -c Release --property:PublishDir=${{ github.workspace }}/publish/AzDo/
      
    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        path: publish/AzDo
        name: ${{ env.ArtifactName }}

  GatherCharacterJsons:
    runs-on: windows-latest
    needs: build
    continue-on-error: true
    concurrency: GatherCharacterJsons-${{ matrix.character }}
    strategy:
      matrix:
        #character: [c,b,e,g,h,j,k,l,m,n,u,w,x,y,z,o,p,r,s,t,v,ai,ae,ia,ea,0,1,2,3,4,5,6,7,8,9]
        character: [9] # temp for faster testing of consolidate updates
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Run Character Command
        uses: ./.github/actions/character-to-run/
        with:
          characters: ${{ matrix.character }}
          artifactName: ${{ env.ArtifactName }}
          # we don't need actual values for these in this job, but they are required
          TwitterConsumerAPIKey: 'TwitterConsumerAPIKey'
          TwitterConsumerAPISecretKey: 'TwitterConsumerAPISecretKey'
          TwitterAccessToken: 'TwitterAccessToken'
          TwitterAccessTokenSecret: 'TwitterAccessTokenSecret'
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

  ConsolidateUpdates:
    runs-on: windows-latest
    needs: GatherCharacterJsons
    concurrency: there-can-only-be-one
    if: ${{ always() }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Download artifact from build job
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ env.artifactName }}
          path: ./ArtifactFolder

      - name: App Settings Variable Substitution
        uses: rajbos-actions/variable-substitution@a4367a66ba128295f7dddf8964a0ac429766492d # v1.1
        with:
          files: 'ArtifactFolder/appsettings.json'
        env:
          TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
          TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
          TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
          TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

      - name: Consolidate the json files and tweet about updates
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          dotnet GitHubActionsNews.dll "consolidate"

      - name: Show consolidated json
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          cat Actions-Updated-Overview.json
          Get-Content Actions-Updated-Overview.json
          // check if the file is empty
          if ((Get-Content Actions-Updated-Overview.json).Length -eq 0) {
            // write something to the file so we can test the next - name: 
            // first create an array to hold the data
            $data = @()
            // add a multiline
            $data += @"
              [            
                {
                  "Url": "https://github.com/marketplace/actions/unity-build-pipeline-utility",
                  "Title": "Unity Build Pipeline Utility",
                  "Publisher": "RageAgainstThePixel",
                  "Version": "v6",
                  "Updated": "2023-08-01T22:22:13.5974967Z",
                  "RepoUrl": "RageAgainstThePixel/unity-build"
                },
                {
                  "Url": "https://github.com/marketplace/actions/setup-kustomizegen",
                  "Title": "Setup Kustomizegen",
                  "Publisher": "josephrodriguez",
                  "Version": "v1-alpha1",
                  "Updated": "2023-08-01T22:22:52.2169806Z",
                  "RepoUrl": "josephrodriguez/setup-kustomizegen"
                },
                {
                  "Url": "https://github.com/marketplace/actions/ai-based-pr-reviewer-summarizer-with-chat-capabilities",
                  "Title": "AI-based PR Reviewer & Summarizer with Chat Capabilities",
                  "Publisher": "coderabbitai",
                  "Version": "1.11.0",
                  "Updated": "2023-08-01T21:58:09.943294Z",
                  "RepoUrl": "coderabbitai/ai-pr-reviewer"
                }
              ]
            "@
          }
          // write the data to the file
          $data | Out-File Actions-Updated-Overview.json -Encoding utf8
      
      - name: Upload Updated Json
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: ArtifactFolder/Actions-Updated-Overview.json
          name: UpdatedActions

  PostNews:
    runs-on: ubuntu-latest
    needs: ConsolidateUpdates
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: UpdatedActions
          path: ./ArtifactFolder

      - name: show data
        run: |
          ls -la
          cat ArtifactFolder/Actions-Updated-Overview.json

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Create blogposts updates for updates
        shell: pwsh
        run: |
          cd .github/workflows/
          ls
          .\createBlogPostsFromUpdates.ps1 -token ${{ secrets.PAT }}
