name: Scheduled Build and Deploy

env:
  ArtifactName: 'AzDoNews'

on:
  schedule:
    - cron: "15 */5 * * *"

  workflow_dispatch:
  
  push:
   paths:
   - .github/workflows/deploy.yml
   - .github/actions/character-to-run/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release --property:OutputPath=publish/AzDo/
      
    - name: Publish
      run: dotnet publish AzDoExtensionNews/AzDoExtensionNews.sln -c Release --property:PublishDir=${{ github.workspace }}/publish/AzDo/
      
    - continue-on-error: true
      run: |
        echo $PWD
        ls -la
        cd publish
        ls -la
        cd AzDo
        ls -la

    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@v3
      with:
        path: publish/AzDo
        name: ${{ env.ArtifactName }}

  GatherCharacterJsons:
    runs-on: windows-latest
    needs: build
    continue-on-error: true
    concurrency: GatherCharacterJsons-${{ matrix.character }}
    strategy:
      matrix:
        character: [c,b,e,g,h,j,k,l,m,n,u,w,x,y,z,o,p,r,s,t,v,ai,ae,ia,ea,0,1,2,3,4,5,6,7,8,9]
    steps:
      - uses: actions/checkout@v3

      - name: Run Character Command
        uses: ./.github/actions/character-to-run/
        with:
          characters: ${{ matrix.character }}
          artifactName: ${{ env.ArtifactName }}
          # we don't need actual values for these in this job, but they are required
          TwitterConsumerAPIKey: 'TwitterConsumerAPIKey'
          TwitterConsumerAPISecretKey: 'TwitterConsumerAPISecretKey'
          TwitterAccessToken: 'TwitterAccessToken'
          TwitterAccessTokenSecret: 'TwitterAccessTokenSecret'
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

  ConsolidateTweet:
    runs-on: windows-latest
    needs: GatherCharacterJsons
    concurrency: there-can-only-be-one
    if: ${{ always() }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: ./ArtifactFolder

      - name: App Settings Variable Substitution
        uses: rajbos-actions/variable-substitution@v1.1
        with:
          files: 'ArtifactFolder/appsettings.json'
        env:
          TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
          TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
          TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
          TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

      - name: Consolidate the json files and tweet about updates
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          dotnet GitHubActionsNews.dll "consolidate"
