name: Tweet Scheduled Build and Deploy

env:
  ArtifactName: 'AzDoNews'

on:
  schedule:
    - cron: "* */4 * * *"
  workflow_dispatch:
  
  push:
   paths:
   - .github/workflows/deploy.yml
   - .github/workflows/templates/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/**.csproj') }}-1

    - name: Restore
      run: dotnet restore AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Build
      run: dotnet build AzDoExtensionNews/AzDoExtensionNews.sln -c Release -o publish/AzDo/

    - name: Test
      run: dotnet test AzDoExtensionNews/AzDoExtensionNews.sln

    - name: Publish AzDo Artifact
      uses: actions/upload-artifact@v2
      with:
        path: publish/AzDo
        name: ${{ env.ArtifactName }}

  GatherCharacterDateJsons:
    runs-on: windows-latest
    needs: build
    continue-on-error: true
    strategy:
      matrix:
        characters: [c,b,e,g,h,j,k,l,m,n,u,w,x,y,z,o,p,r,s,t,v,b,ai,ae,ia,ea,0,1,2,3,4,5,6,7,8,9]
    steps:
      - uses: actions/checkout@v3

      - name: Run Character Command
        uses: ./.github/workflows/templates
        with:
          characters: ${{ matrix.characters }}
          artifactName: ${{ env.ArtifactName }}
          TwitterConsumerAPIKey: 'TwitterConsumerAPIKey'
          TwitterConsumerAPISecretKey: 'TwitterConsumerAPISecretKey'
          TwitterAccessToken: 'TwitterAccessToken'
          TwitterAccessTokenSecret: 'TwitterAccessTokenSecret'
          BlobStorageConnectionString: ${{ secrets.BLOB_CONNECTION_STRING }}

  ConsolidateTweet:
    runs-on: windows-latest
    needs: GatherCharacterDateJsons
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ./ArtifactFolder  


      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'ArtifactFolder/appsettings.json'
        env:
          TwitterConsumerAPIKey: ${{ secrets.TwitterConsumerAPIKey }}
          TwitterConsumerAPISecretKey: ${{ secrets.TwitterConsumerAPISecretKey }}
          TwitterAccessToken: ${{ secrets.TwitterAccessToken }}
          TwitterAccessTokenSecret: ${{ secrets.TwitterAccessTokenSecret }}
          BlobStorageConnectionString: ${{ secrets.BlobStorageConnectionString }}

      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: |
          cd .\ArtifactFolder
          dotnet GitHubActionsNews.dll "consolidate"


