name: Upgrade C# dependencies

on:
  push:
    branches:
      - main

  schedule:
    - cron: '5 2 * * 1' # every Monday

jobs:
  upgrade:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upgrade packages
        run: |
          # get the tool
          dotnet tool install --global dotnet-outdated-tool

          # run the tool
          dotnet outdated --upgrade AzDoExtensionNews\

          # check for any updates with git porcelain
          git status --porcelain Directory.Build.props
          if [[ -n $(git status --porcelain Directory.Build.props) ]]; then
            echo "Committing changes to git and pushing to GitHub..."
            git config --global user.email "bot@github-actions.com"
            git config --global user.name "GitHub Actions Bot"

            git add Directory.Build.props

            git commit -am "chore: upgrade c# dependencies"
            git push

            gh pr create --title "chore: upgrade dependencies" --body "This PR upgrades C# dependencies"
          else
            echo "No changes detected"
          fi